title: Geo-Countries
description: GeoJSON political boundaries of the entire world.
author: Simone Primarosa
logo: /media/geo-countries.png
image: /media/geo-countries.png
show_stargazers: true
exclude:
- CODE_OF_CONDUCT.md
- LICENSE
- README.md
- _config.yml
- package.json
- publish.sh
- gulpfile.js
- utils

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
google_site_verification:
google_analytics:
